# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'LuaTemplate-desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LuaTemplate-desktop

end

target 'LuaTemplate-mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
  pod 'SVProgressHUD'
  pod 'WechatOpenSDK'
  #pod 'Google-Mobile-Ads-SDK'

  # Pods for LuaTemplate-mobile

end
